export interface PortfolioImage {
  src: string;
  alt: string;
  coupleName?: string;
  location?: string;
}

export const portfolioImages: PortfolioImage[] = [
  { src: 'src/assets/portfolio/Anantara_Santorini_1.jpg', alt: 'Anantara Santorini 1', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_10.jpg', alt: 'Anantara Santorini 10', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_11.jpg', alt: 'Anantara Santorini 11', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_12.jpg', alt: 'Anantara Santorini 12', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_13.jpg', alt: 'Anantara Santorini 13', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_14.jpg', alt: 'Anantara Santorini 14', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_15.jpg', alt: 'Anantara Santorini 15', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_2.jpg', alt: 'Anantara Santorini 2', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_3.jpg', alt: 'Anantara Santorini 3', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_4.jpg', alt: 'Anantara Santorini 4', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_5.jpg', alt: 'Anantara Santorini 5', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_6.jpg', alt: 'Anantara Santorini 6', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_7.jpg', alt: 'Anantara Santorini 7', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_8.jpg', alt: 'Anantara Santorini 8', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_9.jpg', alt: 'Anantara Santorini 9', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_E&H_1.jpg', alt: 'Anantara Santorini E&H 1', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_E&H_2.jpg', alt: 'Anantara Santorini E&H 2', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/Anantara_Santorini_E&H_3.jpg', alt: 'Anantara Santorini E&H 3', coupleName: 'Anantara Santorini', location: 'Santorini' },
  { src: 'src/assets/portfolio/1(30).jpg', alt: '1(30)', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/1(39).jpg', alt: '1(39)', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/Aisha&KamilWedding-02424.jpg', alt: 'Aisha&KamilWedding-02424', coupleName: 'Aisha & Kamil', location: 'Wedding' },
  { src: 'src/assets/portfolio/Aisha&KamilWedding-02492.jpg', alt: 'Aisha&KamilWedding-02492', coupleName: 'Aisha & Kamil', location: 'Wedding' },
  { src: 'src/assets/portfolio/DSC02678.jpg', alt: 'DSC02678', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/EOS00554.jpg', alt: 'EOS00554', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/EOS00620.jpg', alt: 'EOS00620', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/EOS00690.jpg', alt: 'EOS00690', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/JPG-001 (1).jpg', alt: 'JPG-001 (1)', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/OLLIE & MARINA_105.JPG', alt: 'OLLIE & MARINA_105', coupleName: 'Ollie & Marina', location: 'Wedding' },
  { src: 'src/assets/portfolio/Park_Haytt_4.jpg', alt: 'Park Haytt 4', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio/Park_Hyatt_1.jpg', alt: 'Park Hyatt 1', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio/Park_Hyatt_2.jpg', alt: 'Park Hyatt 2', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio/Park_Hyatt_3.jpg', alt: 'Park Hyatt 3', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio/Park_Hyatt_5.jpg', alt: 'Park Hyatt 5', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio/Park_Hyatt_6.jpg', alt: 'Park Hyatt 6', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio/Park_Hyatt_7.jpg', alt: 'Park Hyatt 7', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio/PHOTO-2024-10-08-18-18-10 2.jpg', alt: 'PHOTO-2024-10-08-18-18-10 2', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/PHOTO-2024-10-08-18-18-10 3.jpg', alt: 'PHOTO-2024-10-08-18-18-10 3', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/PHOTO-2024-10-08-18-18-14.jpg', alt: 'PHOTO-2024-10-08-18-18-14', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/PHOTO-2024-10-08-18-19-15 2.jpg', alt: 'PHOTO-2024-10-08-18-19-15 2', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/PHOTO-2024-10-08-18-19-17 2.jpg', alt: 'PHOTO-2024-10-08-18-19-17 2', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/photo-257.jpg', alt: 'photo-257', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/photo-262.jpg', alt: 'photo-262', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/T&T-One&Only_Mirrage_1.jpg', alt: 'T&T-One&Only_Mirrage_1', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio/T&T-One&Only_Mirrage_2.jpg', alt: 'T&T-One&Only_Mirrage_2', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio/T&T-One&Only_Mirrage_3.jpg', alt: 'T&T-One&Only_Mirrage_3', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio/T&T-One&Only_Mirrage_4.jpg', alt: 'T&T-One&Only_Mirrage_4', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio/T&T-One&Only_Mirrage_5.jpg', alt: 'T&T-One&Only_Mirrage_5', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio/Twiggy_1.jpg', alt: 'Twiggy_1', coupleName: 'Twiggy', location: 'Unknown Location' },
  { src: 'src/assets/portfolio/Twiggy_2.jpg', alt: 'Twiggy_2', coupleName: 'Twiggy', location: 'Unknown Location' },
];
