export interface PortfolioImage {
  src: string;
  alt: string;
  coupleName?: string;
  location?: string;
}

export const portfolioImages: PortfolioImage[] = [
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_1.webp', alt: 'Anantara Santorini 1', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_10.webp', alt: 'Anantara Santorini 10', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_11.webp', alt: 'Anantara Santorini 11', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_12.webp', alt: 'Anantara Santorini 12', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_13.webp', alt: 'Anantara Santorini 13', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_14.webp', alt: 'Anantara Santorini 14', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_15.webp', alt: 'Anantara Santorini 15', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_2.webp', alt: 'Anantara Santorini 2', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_3.webp', alt: 'Anantara Santorini 3', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_4.webp', alt: 'Anantara Santorini 4', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_5.webp', alt: 'Anantara Santorini 5', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_6.webp', alt: 'Anantara Santorini 6', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_7.webp', alt: 'Anantara Santorini 7', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_8.webp', alt: 'Anantara Santorini 8', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_9.webp', alt: 'Anantara Santorini 9', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_E&H_1.webp', alt: 'Anantara Santorini E&H 1', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_E&H_2.webp', alt: 'Anantara Santorini E&H 2', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/Anantara_Santorini_E&H_3.webp', alt: 'Anantara Santorini E&H 3', coupleName: 'Anantara Santorini', location: 'Abu Dhabi' },
  { src: 'src/assets/portfolio-optimized/1(30).webp', alt: '1(30)', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/1(39).webp', alt: '1(39)', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/Aisha&KamilWedding-02424.webp', alt: 'Aisha&KamilWedding-02424', coupleName: 'Aisha & Kamil', location: 'Wedding' },
  { src: 'src/assets/portfolio-optimized/Aisha&KamilWedding-02492.webp', alt: 'Aisha&KamilWedding-02492', coupleName: 'Aisha & Kamil', location: 'Wedding' },
  { src: 'src/assets/portfolio-optimized/DSC02678.webp', alt: 'DSC02678', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/EOS00554.webp', alt: 'EOS00554', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/EOS00620.webp', alt: 'EOS00620', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/EOS00690.webp', alt: 'EOS00690', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/JPG-001 (1).webp', alt: 'JPG-001 (1)', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/OLLIE & MARINA_105.webp', alt: 'OLLIE & MARINA_105', coupleName: 'Ollie & Marina', location: 'Wedding' },
  { src: 'src/assets/portfolio-optimized/Park_Haytt_4.webp', alt: 'Park Haytt 4', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio-optimized/Park_Hyatt_1.webp', alt: 'Park Hyatt 1', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio-optimized/Park_Hyatt_2.webp', alt: 'Park Hyatt 2', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio-optimized/Park_Hyatt_3.webp', alt: 'Park Hyatt 3', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio-optimized/Park_Hyatt_5.webp', alt: 'Park Hyatt 5', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio-optimized/Park_Hyatt_6.webp', alt: 'Park Hyatt 6', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio-optimized/Park_Hyatt_7.webp', alt: 'Park Hyatt 7', coupleName: 'Park Hyatt', location: 'Dubai' },
  { src: 'src/assets/portfolio-optimized/PHOTO-2024-10-08-18-18-10 2.webp', alt: 'PHOTO-2024-10-08-18-18-10 2', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/PHOTO-2024-10-08-18-18-10 3.webp', alt: 'PHOTO-2024-10-08-18-18-10 3', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/PHOTO-2024-10-08-18-18-14.webp', alt: 'PHOTO-2024-10-08-18-18-14', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/PHOTO-2024-10-08-18-19-15 2.webp', alt: 'PHOTO-2024-10-08-18-19-15 2', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/PHOTO-2024-10-08-18-19-17 2.webp', alt: 'PHOTO-2024-10-08-18-19-17 2', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/photo-257.webp', alt: 'photo-257', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/photo-262.webp', alt: 'photo-262', coupleName: 'Unknown Couple', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/T&T-One&Only_Mirrage_1.webp', alt: 'T&T-One&Only_Mirrage_1', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio-optimized/T&T-One&Only_Mirrage_2.webp', alt: 'T&T-One&Only_Mirrage_2', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio-optimized/T&T-One&Only_Mirrage_3.webp', alt: 'T&T-One&Only_Mirrage_3', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio-optimized/T&T-One&Only_Mirrage_4.webp', alt: 'T&T-One&Only_Mirrage_4', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio-optimized/T&T-One&Only_Mirrage_5.webp', alt: 'T&T-One&Only_Mirrage_5', coupleName: 'T&T', location: 'One&Only Mirage' },
  { src: 'src/assets/portfolio-optimized/Twiggy_1.webp', alt: 'Twiggy_1', coupleName: 'Twiggy', location: 'Unknown Location' },
  { src: 'src/assets/portfolio-optimized/Twiggy_2.webp', alt: 'Twiggy_2', coupleName: 'Twiggy', location: 'Unknown Location' },
];
